# GitLab CI/CD Configuration
stages:
  - lint
  - black
  #  - Uncomment if you want to run tests. make sure to also uncomment the test stage in the pipeline
  - test
  - security

# Cache node_modules for faster builds
cache:
  paths:
    - node_modules/
    - website/node_modules/

# Code style check job
lint:
  stage: lint
  image: node:latest
  script:
    - npm install
    - cd src/website && npm install --legacy-peer-deps && cd ../..
    - npx prettier --check "**/*.{js,jsx,ts,tsx,json,css,html,yaml,markdown,scss}"
  artifacts:
    paths:
      - prettier-report.json
    when: always

# Python code style check job
black:
  stage: black
  image: python:3.11-slim
  script:
    - pip install black>=23.9.1
    - black --check src/backend
  artifacts:
    paths:
      - black-report.json
    when: always

## Test coverage checks for python files
coverage:
  stage: test
  image: python:3.11-slim
  script:
    - pip install -r requirements.txt
    - pytest tests --cov=./src/backend --cov-report=xml --junitxml=test-report.xml
  artifacts:
    reports:
      junit: test-report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - test-report.xml
      - coverage.xml
    when: always
  allow_failure: true
# Dependency security check
dependency-scan:
  stage: security
  image: node:latest
  script:
    - npm install -g npm-audit-resolver
    - npm install
    - cd src/website && npm install --legacy-peer-deps && cd ../..
    - npm audit --production || true
    - cd src/website && npm audit --production || true
  allow_failure: true
  artifacts:
    paths:
      - security-report.txt
      - website-security-report.txt
    when: always
