version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres
    ports:
      #      load the port from the .env file
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d # Load the database schema using the init script
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}

  pgadmin:
    image: dpage/pgadmin4:8.11
    container_name: pgadmin
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  backend:
    build: .
    container_name: backend
    command:
      [
        "/bin/bash",
        "-c",
        "source activate myenv && uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload",
      ]
    #    deploy:
    #      resources:
    #        reservations:
    #          devices:
    #            - driver: nvidia
    #              count: 1
    #              capabilities: [ gpu ]
    expose:
      - 8000
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    depends_on:
      - db
    # For development purposes only
    volumes:
      - .:/app

  website:
    image: node:18
    container_name: website
    working_dir: /website
    command: ["npm", "start"]
    expose:
      - 3000
    volumes:
      - ./website:/website # Mount the website folder to the container
    depends_on:
      - db
  nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - website

volumes:
  postgres_data:
  pgadmin_data:
