version: "3.9"

services:
  tests:
    build: .
    container_name: tests
    command:
      [
        "/bin/bash",
        "-c",
        "source activate myenv && pip install pytest pytest-cov && python -m pytest tests/database_tests/test_user_crud.py -v",
      ]
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/code4meV2
      - TEST_DATABASE_URL=postgresql://postgres:postgres@test_db:5432/test_db
      - PYTHONPATH=/app/src
    volumes:
      - .:/app

volumes:
  postgres_data:
  pgadmin_data:
