"""consolidated schema

Revision ID: 8a0084080b46
Revises: 
Create Date: 2026-09-18 07:43:13.099261

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a0084080b46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acp_capability_receipt',
    sa.Column('receipt_id', sa.UUID(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ide_build', sa.String(), nullable=False),
    sa.Column('ai_assistant_build', sa.String(), nullable=False),
    sa.Column('plugin_version', sa.String(), nullable=False),
    sa.Column('os', sa.String(), nullable=False),
    sa.Column('arch', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('agent_version', sa.String(), nullable=False),
    sa.Column('adapter_version', sa.String(), nullable=True),
    sa.Column('protocol_version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('receipt_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('receipt_id'),
    sa.UniqueConstraint('content_hash'),
    schema='public'
    )
    op.create_index('idx_acp_capability_receipt_agent', 'acp_capability_receipt', ['agent_id', 'agent_version'], unique=False, schema='public')
    op.create_index('idx_acp_capability_receipt_captured_at', 'acp_capability_receipt', ['captured_at'], unique=False, schema='public')
    op.create_index('idx_acp_capability_receipt_status', 'acp_capability_receipt', ['status'], unique=False, schema='public')
    op.create_table('agent_memory',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('owner_project_id', sa.String(), nullable=False),
    sa.Column('memory_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('session_id'),
    schema='public'
    )
    op.create_index('idx_agent_memory_owner_project_id', 'agent_memory', ['owner_project_id'], unique=False, schema='public')
    op.create_index('idx_agent_memory_owner_user_id', 'agent_memory', ['owner_user_id'], unique=False, schema='public')
    op.create_index('idx_agent_memory_updated_at', 'agent_memory', ['updated_at'], unique=False, schema='public')
    op.create_table('agent_release',
    sa.Column('release_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('source_manifest_digest', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('release_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('release_id'),
    sa.UniqueConstraint('agent_id', 'source_manifest_digest', name='uq_agent_release_agent_manifest'),
    schema='public'
    )
    op.create_index('idx_agent_release_agent_id', 'agent_release', ['agent_id'], unique=False, schema='public')
    op.create_index('idx_agent_release_status', 'agent_release', ['status'], unique=False, schema='public')
    op.create_table('provider_connection',
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('secret_ref', sa.String(), nullable=False),
    sa.Column('models_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('connection_id'),
    sa.UniqueConstraint('label'),
    schema='public'
    )
    op.create_index('idx_provider_connection_is_active', 'provider_connection', ['is_active'], unique=False, schema='public')
    op.create_table('research_event',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=True),
    sa.Column('enrollment_id', sa.UUID(), nullable=True),
    sa.Column('research_session_id', sa.UUID(), nullable=True),
    sa.Column('agent_run_id', sa.String(), nullable=True),
    sa.Column('emitter_id', sa.String(), nullable=False),
    sa.Column('emitter_sequence', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('envelope_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('digest', sa.String(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retention_state', sa.String(), server_default='RETAINED', nullable=False),
    sa.Column('anonymized_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('research_session_id', 'emitter_id', 'emitter_sequence', name='uq_research_event_session_emitter_sequence'),
    schema='public'
    )
    op.create_index('idx_research_event_digest', 'research_event', ['digest'], unique=False, schema='public')
    op.create_index('idx_research_event_emitter_id', 'research_event', ['emitter_id'], unique=False, schema='public')
    op.create_index('idx_research_event_enrollment_id', 'research_event', ['enrollment_id'], unique=False, schema='public')
    op.create_index('idx_research_event_event_type', 'research_event', ['event_type'], unique=False, schema='public')
    op.create_index('idx_research_event_occurred_at', 'research_event', ['occurred_at'], unique=False, schema='public')
    op.create_index('idx_research_event_session_id', 'research_event', ['research_session_id'], unique=False, schema='public')
    op.create_table('research_participant',
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('participant_id'),
    sa.UniqueConstraint('account_id'),
    schema='public'
    )
    op.create_index('idx_research_participant_account_id', 'research_participant', ['account_id'], unique=False, schema='public')
    op.create_table('research_record',
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('scope_type', sa.String(), nullable=True),
    sa.Column('scope_id', sa.UUID(), nullable=True),
    sa.Column('study_id', sa.UUID(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('record_id'),
    schema='public'
    )
    op.create_index('idx_research_record_kind', 'research_record', ['kind'], unique=False, schema='public')
    op.create_index('idx_research_record_occurred_at', 'research_record', ['occurred_at'], unique=False, schema='public')
    op.create_index('idx_research_record_scope', 'research_record', ['scope_type', 'scope_id'], unique=False, schema='public')
    op.create_index('idx_research_record_study_id', 'research_record', ['study_id'], unique=False, schema='public')
    op.create_table('research_retention_job',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('evidence_digest', sa.String(), nullable=True),
    sa.Column('affected_events', sa.Integer(), server_default='0', nullable=False),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('enrollment_id', 'action', name='uq_research_retention_job_enrollment_action'),
    schema='public'
    )
    op.create_index('idx_research_retention_job_enrollment', 'research_retention_job', ['enrollment_id'], unique=False, schema='public')
    op.create_index('idx_research_retention_job_state', 'research_retention_job', ['state'], unique=False, schema='public')
    op.create_table('research_session',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('context_id', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_reason', sa.String(), nullable=True),
    sa.Column('resume_generation', sa.Integer(), server_default='0', nullable=False),
    sa.Column('manifest_digest', sa.String(), nullable=False),
    sa.Column('environment_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('transitions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('session_id'),
    schema='public'
    )
    op.create_index('idx_research_session_context_id', 'research_session', ['context_id'], unique=False, schema='public')
    op.create_index('idx_research_session_enrollment_id', 'research_session', ['enrollment_id'], unique=False, schema='public')
    op.create_index('idx_research_session_state', 'research_session', ['state'], unique=False, schema='public')
    op.create_index('idx_research_session_study_id', 'research_session', ['study_id'], unique=False, schema='public')
    op.create_index('uq_research_session_active_context', 'research_session', ['enrollment_id', 'context_id'], unique=True, schema='public', postgresql_where=sa.text("state NOT IN ('ended', 'revoked')"))
    op.create_table('research_agent_run',
    sa.Column('agent_run_id', sa.UUID(), nullable=False),
    sa.Column('research_session_id', sa.UUID(), nullable=True),
    sa.Column('agent_release_id', sa.String(), nullable=True),
    sa.Column('assignment_id', sa.UUID(), nullable=True),
    sa.Column('agent_profile_id', sa.UUID(), nullable=True),
    sa.Column('profile_digest', sa.String(), nullable=True),
    sa.Column('profile_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('snapshot_captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['research_session_id'], ['public.research_session.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_run_id'),
    schema='public'
    )
    op.create_index('idx_research_agent_run_session_id', 'research_agent_run', ['research_session_id'], unique=False, schema='public')
    op.create_table('research_enrollment',
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('participant_code', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('revocation_epoch', sa.Integer(), server_default='0', nullable=False),
    sa.Column('eligibility_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consent_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retention_action', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['public.research_participant.participant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('enrollment_id'),
    sa.UniqueConstraint('participant_id', 'study_id', name='uq_research_enrollment_participant_study'),
    schema='public'
    )
    op.create_index('idx_research_enrollment_participant_code', 'research_enrollment', ['participant_code'], unique=False, schema='public')
    op.create_index('idx_research_enrollment_participant_id', 'research_enrollment', ['participant_id'], unique=False, schema='public')
    op.create_index('idx_research_enrollment_status', 'research_enrollment', ['status'], unique=False, schema='public')
    op.create_index('idx_research_enrollment_study_id', 'research_enrollment', ['study_id'], unique=False, schema='public')
    op.create_index('uq_research_enrollment_active_participant', 'research_enrollment', ['participant_id'], unique=True, schema='public', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_table('agent_profile',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('framework_version', sa.String(), server_default='code4me2-agent', nullable=False),
    sa.Column('release_id', sa.String(), nullable=True),
    sa.Column('connection_id', sa.UUID(), nullable=True),
    sa.Column('tools_json', sa.Text(), nullable=False),
    sa.Column('approval_policy', sa.String(), nullable=False),
    sa.Column('max_steps', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Double(), nullable=True),
    sa.Column('max_context_tokens', sa.Integer(), nullable=True),
    sa.Column('configuration_digest', sa.String(), server_default='', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['public.provider_connection.connection_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['public.user.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['release_id'], ['public.agent_release.release_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('owner_user_id', 'name', name='uq_agent_profile_owner_name'),
    schema='public'
    )
    op.create_index('idx_agent_profile_is_active', 'agent_profile', ['is_active'], unique=False, schema='public')
    op.create_index('idx_agent_profile_owner_user_id', 'agent_profile', ['owner_user_id'], unique=False, schema='public')
    op.create_table('study_assignment',
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('agent_profile_id', sa.UUID(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=False),
    sa.Column('randomization_epoch', sa.Integer(), server_default='0', nullable=False),
    sa.Column('profile_digest', sa.String(), nullable=False),
    sa.Column('profile_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['public.research_enrollment.enrollment_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['agent_profile_id'], ['public.agent_profile.profile_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['study_id'], ['public.study.study_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_id'),
    sa.UniqueConstraint('enrollment_id', name='uq_study_assignment_enrollment'),
    schema='public'
    )
    op.create_index('idx_study_assignment_enrollment_id', 'study_assignment', ['enrollment_id'], unique=False, schema='public')
    op.create_index('idx_study_assignment_study_id', 'study_assignment', ['study_id'], unique=False, schema='public')
    op.create_index('idx_study_assignment_agent_profile_id', 'study_assignment', ['agent_profile_id'], unique=False, schema='public')
    op.create_table('telemetry_batch_receipt',
    sa.Column('receipt_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('enrollment_id', sa.UUID(), nullable=True),
    sa.Column('research_session_id', sa.UUID(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('receipt_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['public.research_enrollment.enrollment_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['research_session_id'], ['public.research_session.session_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('receipt_id'),
    sa.UniqueConstraint('batch_id'),
    schema='public'
    )
    op.create_index('idx_telemetry_batch_receipt_session_id', 'telemetry_batch_receipt', ['research_session_id'], unique=False, schema='public')
    op.create_table('agent_task',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(), server_default='plugin', nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('funding_owner_user_id', sa.UUID(), nullable=True),
    sa.Column('owner_project_id', sa.UUID(), nullable=True),
    sa.Column('external_run_id', sa.String(), nullable=True),
    sa.Column('agent_session_id', sa.String(), nullable=True),
    sa.Column('study_id', sa.UUID(), nullable=True),
    sa.Column('study_assignment_id', sa.UUID(), nullable=True),
    sa.Column('research_session_id', sa.UUID(), nullable=True),
    sa.Column('enrollment_id', sa.UUID(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('agent_profile', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('temperature', sa.Double(), nullable=True),
    sa.Column('approval_policy', sa.String(), nullable=False),
    sa.Column('tools_json', sa.Text(), nullable=False),
    sa.Column('framework_version', sa.String(), nullable=True),
    sa.Column('policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('observed_framework_version', sa.String(), nullable=True),
    sa.Column('observed_tools_json', sa.Text(), nullable=True),
    sa.Column('consent_content_storage', sa.Boolean(), nullable=True),
    sa.Column('next_event_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latest_event_id', sa.UUID(), nullable=True),
    sa.Column('task_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['funding_owner_user_id'], ['public.user.user_id'], ondelete='SET NULL'),
    # The cyclic latest_event_id FK is added explicitly after both tables exist
    # (declared use_alter=True in the model, so it is not created inline here).
    sa.ForeignKeyConstraint(['owner_user_id'], ['public.user.user_id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['public.agent_profile.profile_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['public.session.session_id'], ),
    sa.ForeignKeyConstraint(['study_assignment_id'], ['public.study_assignment.assignment_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['study_id'], ['public.study.study_id'], ),
    sa.PrimaryKeyConstraint('task_id'),
    sa.UniqueConstraint('external_run_id'),
    schema='public'
    )
    op.create_index('idx_agent_task_enrollment_id', 'agent_task', ['enrollment_id'], unique=False, schema='public')
    op.create_index('idx_agent_task_owner_user_id', 'agent_task', ['owner_user_id'], unique=False, schema='public')
    op.create_index('idx_agent_task_profile_id', 'agent_task', ['profile_id'], unique=False, schema='public')
    op.create_index('idx_agent_task_research_session_id', 'agent_task', ['research_session_id'], unique=False, schema='public')
    op.create_index('idx_agent_task_session_id', 'agent_task', ['session_id'], unique=False, schema='public')
    op.create_index('idx_agent_task_status', 'agent_task', ['status'], unique=False, schema='public')
    op.create_index('idx_agent_task_study_assignment_id', 'agent_task', ['study_assignment_id'], unique=False, schema='public')
    op.create_index('idx_agent_task_study_id', 'agent_task', ['study_id'], unique=False, schema='public')
    op.create_table('agent_edit',
    sa.Column('edit_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('was_accepted', sa.Boolean(), nullable=True),
    sa.Column('was_modified', sa.Boolean(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('diff_text', sa.Text(), nullable=True),
    sa.Column('edit_delta_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['public.agent_task.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('edit_id'),
    schema='public'
    )
    op.create_index('idx_agent_edit_task_id', 'agent_edit', ['task_id'], unique=False, schema='public')
    op.create_table('agent_event',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('event_index', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_event_id', sa.String(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('span_id', sa.String(), nullable=True),
    sa.Column('parent_span_id', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('chat_session_index', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('agent_profile', sa.String(), nullable=True),
    sa.Column('streaming', sa.Boolean(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('role_system_count', sa.Integer(), nullable=True),
    sa.Column('role_user_count', sa.Integer(), nullable=True),
    sa.Column('role_assistant_count', sa.Integer(), nullable=True),
    sa.Column('role_tool_count', sa.Integer(), nullable=True),
    sa.Column('tools_kept', sa.Integer(), nullable=True),
    sa.Column('tools_stripped', sa.Integer(), nullable=True),
    sa.Column('tool_names_requested', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('finish_reason', sa.String(), nullable=True),
    sa.Column('upstream_status', sa.Integer(), nullable=True),
    sa.Column('step_index', sa.Integer(), nullable=True),
    sa.Column('context_window_size_bytes', sa.Integer(), nullable=True),
    sa.Column('active_file', sa.Text(), nullable=True),
    sa.Column('first_message_hash', sa.String(), nullable=True),
    sa.Column('chat_new_session_detected', sa.Boolean(), nullable=True),
    sa.Column('experiment_tool_access_enabled', sa.Boolean(), nullable=True),
    sa.Column('experiment_approval_policy', sa.String(), nullable=True),
    sa.Column('first_system_message', sa.Text(), nullable=True),
    sa.Column('last_user_message', sa.Text(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('tool_arguments_length', sa.Integer(), nullable=True),
    sa.Column('tool_result_length', sa.Integer(), nullable=True),
    sa.Column('tool_arguments', sa.Text(), nullable=True),
    sa.Column('tool_result', sa.Text(), nullable=True),
    sa.Column('extra_json', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['public.agent_task.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('task_id', 'event_index', name='uq_agent_event_task_event_index'),
    sa.UniqueConstraint('task_id', 'source', 'source_event_id', name='uq_agent_event_source_identity'),
    schema='public'
    )
    op.create_index('idx_agent_event_created_at', 'agent_event', ['created_at'], unique=False, schema='public')
    op.create_index('idx_agent_event_event_type', 'agent_event', ['event_type'], unique=False, schema='public')
    op.create_index('idx_agent_event_task_id', 'agent_event', ['task_id'], unique=False, schema='public')
    op.add_column('study', sa.Column('is_research', sa.Boolean(), server_default='false', nullable=False), schema='public')
    op.add_column('study', sa.Column('research_status', sa.String(), nullable=True), schema='public')
    op.add_column('study', sa.Column('research_config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='public')
    op.add_column('study', sa.Column('research_config_digest', sa.String(), nullable=True), schema='public')
    op.add_column('study', sa.Column('join_code', sa.String(), nullable=True), schema='public')
    op.add_column('study', sa.Column('consent_locked_at', sa.DateTime(timezone=True), nullable=True), schema='public')
    op.add_column('study', sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True), schema='public')
    op.add_column('study', sa.Column('stopped_by', sa.String(), nullable=True), schema='public')
    op.create_table('study_agent_profile',
    sa.Column('study_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('profile_digest', sa.String(), nullable=False),
    sa.Column('profile_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('selection_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['public.agent_profile.profile_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['study_id'], ['public.study.study_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('study_id', 'profile_id'),
    sa.UniqueConstraint('study_id', 'profile_id', name='uq_study_agent_profile_selection'),
    schema='public'
    )
    op.create_index('idx_study_agent_profile_profile_id', 'study_agent_profile', ['profile_id'], unique=False, schema='public')
    op.alter_column('study', 'default_config_id',
               existing_type=sa.BIGINT(),
               nullable=True,
               schema='public')
    op.create_index('idx_study_research_status', 'study', ['research_status'], unique=False, schema='public')
    op.create_index('uq_study_research_join_code', 'study', ['join_code'], unique=True, schema='public', postgresql_where=sa.text('is_research AND join_code IS NOT NULL'))
    op.add_column('user', sa.Column('can_research', sa.Boolean(), server_default='false', nullable=False), schema='public')
    op.create_index('idx_user_can_research', 'user', ['can_research'], unique=False, schema='public')
    # Cyclic FK (agent_task.latest_event_id -> agent_event.event_id) declared
    # with use_alter=True in the model, so autogenerate skips it. Added by hand
    # after both tables exist.
    # Research referential integrity (M02). Ownership/enrollment/study are
    # real relationships; telemetry uses SET NULL so retention policy, not a
    # parent-row delete, decides when events disappear.
    op.create_foreign_key('fk_research_participant_account', 'research_participant', 'user', ['account_id'], ['user_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key('fk_research_session_enrollment', 'research_session', 'research_enrollment', ['enrollment_id'], ['enrollment_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key('fk_research_session_study', 'research_session', 'study', ['study_id'], ['study_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key('fk_research_event_study', 'research_event', 'study', ['study_id'], ['study_id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key('fk_research_event_enrollment', 'research_event', 'research_enrollment', ['enrollment_id'], ['enrollment_id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key('fk_research_event_session', 'research_event', 'research_session', ['research_session_id'], ['session_id'], source_schema='public', referent_schema='public', ondelete='SET NULL')
    op.create_foreign_key(
        'agent_task_latest_event_id_fkey',
        'agent_task',
        'agent_event',
        ['latest_event_id'],
        ['event_id'],
        source_schema='public',
        referent_schema='public',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    for _name, _table in (
        ('fk_research_event_session', 'research_event'),
        ('fk_research_event_enrollment', 'research_event'),
        ('fk_research_event_study', 'research_event'),
        ('fk_research_session_study', 'research_session'),
        ('fk_research_session_enrollment', 'research_session'),
        ('fk_research_participant_account', 'research_participant'),
    ):
        op.drop_constraint(_name, _table, schema='public', type_='foreignkey')
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_can_research', table_name='user', schema='public')
    op.drop_column('user', 'can_research', schema='public')
    op.drop_index('uq_study_research_join_code', table_name='study', schema='public', postgresql_where=sa.text('is_research AND join_code IS NOT NULL'))
    op.drop_index('idx_study_research_status', table_name='study', schema='public')
    op.drop_index('idx_study_agent_profile_profile_id', table_name='study_agent_profile', schema='public')
    op.drop_table('study_agent_profile', schema='public')
    op.drop_column('study', 'stopped_by', schema='public')
    op.drop_column('study', 'stopped_at', schema='public')
    op.drop_column('study', 'consent_locked_at', schema='public')
    op.drop_column('study', 'join_code', schema='public')
    op.drop_column('study', 'research_config_digest', schema='public')
    op.drop_column('study', 'research_config_json', schema='public')
    op.drop_column('study', 'research_status', schema='public')
    op.alter_column('study', 'default_config_id',
               existing_type=sa.BIGINT(),
               nullable=False,
               schema='public')
    op.drop_column('study', 'is_research', schema='public')
    op.drop_index('idx_agent_event_task_id', table_name='agent_event', schema='public')
    op.drop_index('idx_agent_event_event_type', table_name='agent_event', schema='public')
    op.drop_index('idx_agent_event_created_at', table_name='agent_event', schema='public')
    op.drop_constraint('agent_task_latest_event_id_fkey', 'agent_task', schema='public', type_='foreignkey')
    op.drop_table('agent_event', schema='public')
    op.drop_index('idx_agent_edit_task_id', table_name='agent_edit', schema='public')
    op.drop_table('agent_edit', schema='public')
    op.drop_index('idx_agent_task_study_id', table_name='agent_task', schema='public')
    op.drop_index('idx_agent_task_study_assignment_id', table_name='agent_task', schema='public')
    op.drop_index('idx_agent_task_status', table_name='agent_task', schema='public')
    op.drop_index('idx_agent_task_session_id', table_name='agent_task', schema='public')
    op.drop_index('idx_agent_task_research_session_id', table_name='agent_task', schema='public')
    op.drop_index('idx_agent_task_profile_id', table_name='agent_task', schema='public')
    op.drop_index('idx_agent_task_owner_user_id', table_name='agent_task', schema='public')
    op.drop_index('idx_agent_task_enrollment_id', table_name='agent_task', schema='public')
    op.drop_table('agent_task', schema='public')
    op.drop_index('idx_telemetry_batch_receipt_session_id', table_name='telemetry_batch_receipt', schema='public')
    op.drop_table('telemetry_batch_receipt', schema='public')
    op.drop_index('idx_study_assignment_agent_profile_id', table_name='study_assignment', schema='public')
    op.drop_index('idx_study_assignment_study_id', table_name='study_assignment', schema='public')
    op.drop_index('idx_study_assignment_enrollment_id', table_name='study_assignment', schema='public')
    op.drop_table('study_assignment', schema='public')
    op.drop_index('idx_agent_profile_owner_user_id', table_name='agent_profile', schema='public')
    op.drop_index('idx_agent_profile_is_active', table_name='agent_profile', schema='public')
    op.drop_table('agent_profile', schema='public')
    op.drop_index('uq_research_enrollment_active_participant', table_name='research_enrollment', schema='public', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index('idx_research_enrollment_study_id', table_name='research_enrollment', schema='public')
    op.drop_index('idx_research_enrollment_status', table_name='research_enrollment', schema='public')
    op.drop_index('idx_research_enrollment_participant_id', table_name='research_enrollment', schema='public')
    op.drop_index('idx_research_enrollment_participant_code', table_name='research_enrollment', schema='public')
    op.drop_table('research_enrollment', schema='public')
    op.drop_index('idx_research_agent_run_session_id', table_name='research_agent_run', schema='public')
    op.drop_table('research_agent_run', schema='public')
    op.drop_index('uq_research_session_active_context', table_name='research_session', schema='public', postgresql_where=sa.text("state NOT IN ('ended', 'revoked')"))
    op.drop_index('idx_research_session_study_id', table_name='research_session', schema='public')
    op.drop_index('idx_research_session_state', table_name='research_session', schema='public')
    op.drop_index('idx_research_session_enrollment_id', table_name='research_session', schema='public')
    op.drop_index('idx_research_session_context_id', table_name='research_session', schema='public')
    op.drop_table('research_session', schema='public')
    op.drop_index('idx_research_retention_job_state', table_name='research_retention_job', schema='public')
    op.drop_index('idx_research_retention_job_enrollment', table_name='research_retention_job', schema='public')
    op.drop_table('research_retention_job', schema='public')
    op.drop_index('idx_research_record_study_id', table_name='research_record', schema='public')
    op.drop_index('idx_research_record_scope', table_name='research_record', schema='public')
    op.drop_index('idx_research_record_occurred_at', table_name='research_record', schema='public')
    op.drop_index('idx_research_record_kind', table_name='research_record', schema='public')
    op.drop_table('research_record', schema='public')
    op.drop_index('idx_research_participant_account_id', table_name='research_participant', schema='public')
    op.drop_table('research_participant', schema='public')
    op.drop_index('idx_research_event_session_id', table_name='research_event', schema='public')
    op.drop_index('idx_research_event_occurred_at', table_name='research_event', schema='public')
    op.drop_index('idx_research_event_event_type', table_name='research_event', schema='public')
    op.drop_index('idx_research_event_enrollment_id', table_name='research_event', schema='public')
    op.drop_index('idx_research_event_emitter_id', table_name='research_event', schema='public')
    op.drop_index('idx_research_event_digest', table_name='research_event', schema='public')
    op.drop_table('research_event', schema='public')
    op.drop_index('idx_provider_connection_is_active', table_name='provider_connection', schema='public')
    op.drop_table('provider_connection', schema='public')
    op.drop_index('idx_agent_release_status', table_name='agent_release', schema='public')
    op.drop_index('idx_agent_release_agent_id', table_name='agent_release', schema='public')
    op.drop_table('agent_release', schema='public')
    op.drop_index('idx_agent_memory_updated_at', table_name='agent_memory', schema='public')
    op.drop_index('idx_agent_memory_owner_user_id', table_name='agent_memory', schema='public')
    op.drop_index('idx_agent_memory_owner_project_id', table_name='agent_memory', schema='public')
    op.drop_table('agent_memory', schema='public')
    op.drop_index('idx_acp_capability_receipt_status', table_name='acp_capability_receipt', schema='public')
    op.drop_index('idx_acp_capability_receipt_captured_at', table_name='acp_capability_receipt', schema='public')
    op.drop_index('idx_acp_capability_receipt_agent', table_name='acp_capability_receipt', schema='public')
    op.drop_table('acp_capability_receipt', schema='public')
    # ### end Alembic commands ###