#!/usr/bin/env python3
"""Stamp the immutable version reported by a packaged runtime binary."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

SEMVER = re.compile(
    r"[0-9]+\.[0-9]+\.[0-9]+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?\Z"
)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--version", required=True)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("src/code4me2_agent/_build_version.py"),
    )
    args = parser.parse_args()
    if not SEMVER.fullmatch(args.version):
        raise SystemExit(f"runtime version must be SemVer: {args.version!r}")
    args.output.write_text(
        '"""Generated by packaging/stamp_runtime_version.py."""\n\n'
        f'RUNTIME_VERSION = "{args.version}"\n',
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
